### ISSUE TITLE
 No such file or directory - connect(2) for /var/run/dbus/system_bus_socket

### ISSUE THREAD

**Issue by tarun-pacifica** [sdalu/ruby-ble#1]
cant require ble. full error message below

2.3.1 :001 > require 'ble'
Errno::ENOENT: No such file or directory - connect(2) for /var/run/dbus/system_bus_socket
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/message_queue.rb:115:in `connect'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/message_queue.rb:115:in`connect_to_unix'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/message_queue.rb:67:in `block in connect'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/message_queue.rb:56:in`each'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/message_queue.rb:56:in `find'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/message_queue.rb:56:in`connect'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/message_queue.rb:22:in `initialize'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/bus.rb:199:in`new'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/bus.rb:199:in `initialize'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/bus.rb:646:in`initialize'
    from /Users/MOOKBOOK13/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/singleton.rb:142:in `new'
    from /Users/MOOKBOOK13/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/singleton.rb:142:in`block in instance'
    from /Users/MOOKBOOK13/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/singleton.rb:140:in `synchronize'
    from /Users/MOOKBOOK13/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/singleton.rb:140:in`instance'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ruby-dbus-0.11.1/lib/dbus/bus.rb:679:in `system_bus'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ble-0.0.2/lib/ble.rb:44:in`module:BLE'
    from /Users/MOOKBOOK13/.rvm/gems/ruby-2.3.1/gems/ble-0.0.2/lib/ble.rb:10:in `<top (required)>'
    from /Users/MOOKBOOK13/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in`require'
    from /Users/MOOKBOOK13/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
    from /Users/MOOKBOOK13/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in`require'
    from (irb):1
    from /Users/MOOKBOOK13/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'

**Comment by sdalu** [comment]
The librarie requires dbus, are you using DBus on your system?

**Comment by tarun-pacifica** [comment]
documentation says: ble 0.0.2 - depends on github-markup, rake, redcarpet, ruby-dbus, yard.
I have installed all of the above dependencies. 
i note there is a separate gem 'dbus' available? I have been unable to install that one as per attached makefile notes.
[mkmf.log.zip](https://github.com/sdalu/ruby-ble/files/317457/mkmf.log.zip)

**Comment by sdalu** [comment]
I was talking about the dbus system process, that's the one creating the system_bus_socket file.
It seems you are using a Mac, I'm not sure there is such dbus process running on it.

I've found a link that could be useful:
https://gist.github.com/TheFox/dc3f1b88757ba0a8a7a9
